name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: browser-actions/setup-chrome@latest
      - run: npm install
      - run: COVERAGE=true npm run build:test
      - run: COVERAGE=true npm run test:ember --path dist
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
